# Docker Lemp for Magento applications
version: "3"

services:
  app:
    image: lima195/laravel-nginx:latest
    # build: 
    #   context: .
    #   dockerfile: ./images/nginx/Dockerfile
    ports:
      - "80:8000"
      - "443:8443"
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:cached
      - ~/.ssh/id_rsa:/var/www/.ssh/id_rsa:cached
      - ~/.ssh/known_hosts:/var/www/.ssh/known_hosts:cached
      - appdata:/var/www/html
      - sockdata:/sock
      - ssldata:/etc/nginx/certs

  phpfpm:
    image: lima195/laravel-php-fpm8.2:latest
    # build: 
    #   context: .
    #   dockerfile: ./images/php/Dockerfile
    volumes: *appvolumes
    env_file: env/phpfpm.env

  db:
    image: mariadb:10.6
    command:
      --max_allowed_packet=64M
      --optimizer_use_condition_selectivity=1
      --optimizer_switch="rowid_filter=off"
    ports:
      - "3306:3306"
    env_file: env/db.env
    volumes:
      - dbdata:/var/lib/mysql

  redis:
    image: redis:6.2-alpine
    ports:
      - "6379:6379"

  mailcatcher:
    image: sj26/mailcatcher
    ports:
      - "1080:1080"

volumes:
  appdata:
  dbdata:
  rabbitmqdata:
  sockdata:
  ssldata:
